### ISSUE TITLE
Shadow DOM

### ISSUE THREAD

**Issue by pablomayobre** [whizkydee/material-palenight-syntax#1]
[Atom recently deprecated the use of Shadow DOM](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html) so currently material-palenight-syntax appears in the deprecation cop, for using deprecated styles, this is an easy fix, I can make a PR if you want.

**Comment by pablomayobre** [comment]
I started to work at this over at Positive07/material-palenight-syntax@239e9424f32b8c5 but I still have to test it, also I didn't change styles that referred to `.sublimelinter` since I don't really know why you have those. Deprecation Cop may complain about them though so if they are not needed I recommend you remove them.

PS: Atom 1.13.0 is not released, but it will be released soon, I'm using a beta release (atom-1.13.0-beta8-ia32)

**Comment by whizkydee** [comment]
Thanks @Positive07,

Looks awesome! 👍. Feel free to send a PR. And I'll merge once `v1.13.0` is out. Perhaps, I'd love support for `>=1.0.0`, so I might need to use both styles.

**Comment by pablomayobre** [comment]
I recommend you drop 1.0.0 support, older Atom versions would actually get the current theme and not this one because of the dependency in the packages.json, so there should be no problems.

Also if you give support to both it will still show up in the deprecation cop which is not nice. I'll test this out and make a PR when I'm entirely sure this works and fixes the issue of the deprecation cop, I'm still worried that those sublimelinter themes will show up, can you tell me what are them?

**Comment by whizkydee** [comment]
Thanks @Positive07,
I'll respond shortly.

**Comment by pablomayobre** [comment]
I'll have to rebase this since I see that you have made a new release! But I would prefere to wait a little more since Atom 1.13 is not yet released

**Comment by whizkydee** [comment]
Great @Positive07. I'd be expecting the PR when `v1.13` is released.
