### ISSUE TITLE
Random version bumps

### ISSUE THREAD

**Issue by IanCaunce** [whizkydee/material-palenight-syntax#3]
I am curious as to why there have been several random version bumps and new releases without any actual changes to code?

https://github.com/whizkydee/atom-material-palenight-syntax/compare/v1.4.0...v1.4.1
https://github.com/whizkydee/atom-material-palenight-syntax/compare/v1.4.1...v1.4.3
https://github.com/whizkydee/atom-material-palenight-syntax/compare/v1.4.4...v1.4.5

I check each package when they are updated in atom and I noticed that nothing is really being updated in your package between the versions above.

**Comment by whizkydee** [comment]
Hi @IanCaunce,

First off, I so much appreciate your observation and the fact that you check this repo each time there's an update – that's awesome! 👍 

However, it's important to state that the reason for the version bumps without changes to the code base is that once an Atom package or theme is updated, Atom automatically registers it in the **Recently Updated** section on [their site](https://atom.io/themes/) which helps promote the theme or package.

From my discovery, the more a new version gets published, the more the theme or package gets displayed to people which eventually results to more downloads, and that's cool! 😄😄

I hope that answers your question. 😏

**Comment by IanCaunce** [comment]
Thanks for the quick reply!

Although I can understand your reasoning for doing this as its a cheap and effective method of self promotion, I am not sure I agree with it as it will force your entire userbase to have to re-download the theme with every bump for no benefit to them. It also gives the false impression that it is being actively maintained. I know yours is as I can see many other releases which include new features and code changes. If every package did it, it would render atom's "Recently Updated" section useless.

Edit: Apologies for closing the issue. I clicked the wrong button. Happy the query has been explained however if you want to close it.

**Comment by whizkydee** [comment]
@IanCaunce,
They don't have to ’re-download’ the theme, they'll just have to update it.

**Comment by IanCaunce** [comment]
I don't know enough about how atom handles updates and whether it downloads just the differences between files. Apologies if my comment was incorrect/misleading.
