### ISSUE TITLE
Deprecated selector in `material-palenight-syntax/index.less`

### ISSUE THREAD

**Issue by IanCaunce** [whizkydee/material-palenight-syntax#4]
Just noticed a deprecation warning in your latest update.

Auto-generated by atom:

In `material-palenight-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.syntax--entity.syntax--name.syntax--function,
.entity.syntax--name.syntax--function,
.syntax--meta.syntax--require,
.syntax--support.syntax--function.syntax--any-method,
.syntax--meta.syntax--function-call,
.syntax--support.syntax--function,
.syntax--keyword.syntax--other.syntax--special-method,
.syntax--meta.syntax--block-level,
.syntax--meta.syntax--function-call.syntax--method.syntax--with-arguments .syntax--variable.syntax--function` => `.syntax--entity.syntax--name.syntax--function,
.syntax--entity.syntax--name.syntax--function,
.syntax--meta.syntax--require,
.syntax--support.syntax--function.syntax--any-method,
.syntax--meta.syntax--function-call,
.syntax--support.syntax--function,
.syntax--keyword.syntax--other.syntax--special-method,
.syntax--meta.syntax--block-level,
.syntax--meta.syntax--function-call.syntax--method.syntax--with-arguments .syntax--variable.syntax--function`

* `.syntax--tsx.entity.syntax--name.syntax--function,
.syntax--tsx.syntax--entity.syntax--name.syntax--function` => `.syntax--tsx.syntax--entity.syntax--name.syntax--function,
.syntax--tsx.syntax--entity.syntax--name.syntax--function`

* `.syntax--variable.syntax--parameter.syntax--tsx,
.syntax--entity.syntax--name.syntax--function.syntax--tsx,
.entity.syntax--name.syntax--function.syntax--tsx,
.syntax--property.syntax--function.syntax--tsx` => `.syntax--variable.syntax--parameter.syntax--tsx,
.syntax--entity.syntax--name.syntax--function.syntax--tsx,
.syntax--entity.syntax--name.syntax--function.syntax--tsx,
.syntax--property.syntax--function.syntax--tsx`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by whizkydee** [comment]
Thanks @IanCaunce ,

Actually, that was intentional. There's a particular [TypeScript package](https://atom.io/packages/atom-typescript) that still adds an `entity` class name to a particular syntax selector.

I was trying to make sure that it gets highlighted, but I forgot that Atom automatically transforms the selectors. So I'll raise an issue on their GitHub repo about the deprecation and fix that.

See this image for more clarification;
![Deprecated Selector](http://i.imgur.com/CPV0DP4.png)
